spring:
  profiles:
    active: production

  application:
    name: j316-cell
  devtools.restart.enabled: true

server:
  port: 8081

cell:
  ip: 192.168.0.248
  port: 5005
  connection.timeout: 1000