spring:
  profiles:
    active: production

  application:
    name: j316-cell

server:
  port: 8081
  servlet:
    session:
      timeout: 180m
      tracking-modes: cookie
      cookie:
        max-age: 360m
        name: chorzeile
        comment: session authentification for chorzeile

adapter:
  cell:
    ip: 192.168.0.248
    port: 5005
    connection.timeout: 1000

  security:
    username: test
    password: test