spring:
  profiles:
    active: production

  application:
    name: j316-cell

  security:
    oauth2:
      client:
        registration:
          auth0:
            provider: auth0
            client-id: ${AUTH0_CLIENT_ID:dummy-client-id}
            client-secret: ${AUTH0_CLIENT_SECRET:dummy-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

        provider:
          auth0:
            authorization-uri: ${AUTH0_AUTHORIZATION_URI:https://christen-frankfurt.eu.auth0.com/authorize}
            token-uri: ${AUTH0_TOKEN_URI:https://christen-frankfurt.eu.auth0.com/oauth/token}
            user-info-uri: ${AUTH0_USER_INFO_URI:https://christen-frankfurt.eu.auth0.com/userinfo}
            jwk-set-uri: ${AUTH0_JWK_SET_URI:https://christen-frankfurt.eu.auth0.com/.well-known/jwks.json}
            user-name-attribute: sub

      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://christen-frankfurt.eu.auth0.com/}
server:
  port: 8081
  servlet:
    session:
      timeout: 180m
      tracking-modes: cookie
      cookie:
        max-age: 360m
        name: chorzeile

adapter:
  cell:
    ip: localhost
    port: 5005
    connection.timeout: 1000

  security:
    username: ${BASIC_AUTH_USERNAME:test}
    password: ${BASIC_AUTH_PASSWORD:test}
    auth0:
      enabled: ${AUTH0_ENABLED:false}
      audience: ${AUTH0_AUDIENCE:cell-control-api}
